---
# Copyright 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

galaxy_info:
  author: VEXXHOST, Inc.
  description: Ansible role for Prometheus Blackbox exporter
  license: Apache-2.0
  min_ansible_version: 2.10
  standalone: false
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: defaults
  - role: vexxhost.kubernetes.upload_helm_chart
    vars:
      upload_helm_chart_src: "{{ prometheus_blackbox_exporter_helm_chart_path }}"
      upload_helm_chart_dest: "{{ prometheus_blackbox_exporter_helm_chart_ref }}"
